module_D/D14_Module_localization/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [

    path('i18n/', include('django.conf.urls.i18n')), # подключаем встроенные эндопинты для работы с локализацией
    path('', include('protect.urls')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('sign/', include('sign.urls')),
    path('account/', include('allauth.urls')),
    path('news/', include('newapp.urls')),
        ]

# добавление маршрута к медиа - нужно джанге только в ОТЛАДОЧНОМ режиме
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

module_D/D14_Module_localization/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView, upgrade_me

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name = 'sign/login.html'),
         # LoginView.as_view(template_name = 'account/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name = 'sign/logout.html'),
         name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name = 'sign/signup.html'),
         name='signup'),
    path('upgrade/', upgrade_me, name = 'upgrade')
]

module_D/D14_Module_localization/newapp/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.cache import cache
from django.utils.translation import gettext as _
# from django.utils.translation import ugettext_lazy as _# импортируем «ленивый» геттекст с подсказкой



class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.FloatField(default=0.0)

    def update_rating(self):
        # каждой статьи автора
        posts_author = Post.objects.filter(author=self.id)
        author_rating_new = 0
        for _ in posts_author.all().values('rating_new_post'):
            author_rating_new += _['rating_new_post']
        author_rating_new = author_rating_new*3

        # всех комментариев автора
        comm_auth = Comment.objects.filter(author=self.id)
        comm_auth_new = 0
        for _ in comm_auth.all().values('rating_comment'):
            comm_auth_new += _['rating_comment']

        # всех комментариев к статьям автора
        comm_post_auth = Post.objects.filter(author = self).values('rating_new_post')
        comm_post_auth_new = 0
        for _ in comm_post_auth:
            comm_post_auth_new += _['rating_new_post']

        # print("рейтинг обновлен, ", self.author_rating)
        self.author_rating = self.author_rating + author_rating_new \
                             + comm_auth_new + comm_post_auth_new
        self.save()

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        # return f'{self.title}: {self.content_new_post[:125]}...'
        return f'{self.author}'


class Category(models.Model):
    category_name = models.CharField(max_length=30, unique=True, null=False, help_text=_('название категории'))  # переводящийся текст подсказку к полю
    subscriber = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'



class Post(models.Model):
    post = "PO"
    new = "NE"
    POST_NEW = [(post, "статья"), (new,"новость")]
    new_post = models.CharField(max_length = 2, choices = POST_NEW, default = post, verbose_name="Тип")
    time_in_new_post = models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")
    title = models.CharField(max_length=150, verbose_name="Заголовок", null=False)
    content_new_post = models.TextField(null=False, verbose_name="Текст",)
    rating_new_post = models.FloatField(default=0.0, verbose_name="Рейтинг")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name="Фото", blank=True)
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name="Обновлено")

    category = models.ManyToManyField(Category, through='PostCategory')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def like(self):
        self.rating_new_post += 1
        self.save()

    def dislike(self):
        self.rating_new_post += 1
        self.save()

    def preview(self):
        return f'{self.content_new_post[:125]}...'

    def get_absolute_url(self):
        return f'/news/{self.id}'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def save(self, *args, **kwargs):                 # переопределение для обновления ключей кеша конкретной новости (смотри PostDetailView)
        super().save(*args, **kwargs)                # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'new_post-{self.pk}')          # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False)


class Comment(models.Model):
    content_comments = models.CharField(max_length=255)
    time_in_comment = models.DateTimeField(auto_now_add=True)
    rating_comment = models.FloatField(default=0.0)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def like(self):
        self.rating_comment += 1
        self.save()

    def dislike(self):
        self.rating_comment -= 1
        self.save()

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    # def __str__(self):
    #     return self.content_comments


class UserCategory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

module_D/D14_Module_localization/templates/mail_new_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message</title>
</head>
<body>
    <h2>Здравствуй, {{ appointment.client_name }}!</h2>
    <p> Новая статья в твоём любимом разделе!


     {{ appointment.date|date:"d-M-Y" }} по вопросу: {{ appointment.message|truncatechars:50 }} </p>


</body>
</html>



{% comment %}
И при добавлении новости из этой категории пользователю на email,
указанный при регистрации, будет приходить письмо с


Текст состоит из вышеуказанного HTML и текста:
.{% endcomment %}


теМА - сам заголовок статьи.
ТЕКСТ - «Здравствуй, username. Новая статья в твоём любимом разделе!»
        ЗАГОЛОВОК И  первых 50 символов текста статьи.

module_D/D14_Module_localization/templates/make_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make an appointment</title>
</head>
<body>
    <h1>Make an appointment</h1>
    <form method="post">
    <div class="form-actions form-group ">
        {% csrf_token %}
        <label for="client_name">Your name</label>
        <input type="text" name="client_name"><br>
        <label for="message"> Short description of your issue</label>
        <input type="text" name="message"><br>
        <label for="date">Choose time</label>
        <input type="data" name="date">.<br>
        <input type="submit">
    </div>
    </form>
</body>
</html>

module_D/D14_Module_localization/templates/post_create.html
{% extends 'flatpages/default.html' %}
{% load censor %} <!-- не забываем заранее загружать наши фильтры! -->
{% block title %} Post_add {% endblock title %}
{% load i18n %}
{% block content %}


<br> <h2> {% trans 'Добавление публикации' %} </h2><hr><br>


{% if publications_for_today_limit %}

<p><a>{% trans 'Ваш лимит публикаций на сегодня' %}: </a> {{publications_for_today_limit}} </p>


{#{% load cache %} <!-- Загружаем кэширование -->#}
{#    {% cache 10 header %} <!-- Кэшируем отдельный блок на 30 секунд -->#}
        {% block header %}

    <form method='POST' class="form-control">
        {% csrf_token %}
        {{ form.non_field.errors }}

        <div class="form-group">
            <label for="{{ form.title.id_for_label }}"> {% trans 'Заголовок' %} </label>
            {{ form.title }}
            <div class="invalid-feedback">
                {{ form.title.errors }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.content_new_post.id_for_label }}"> {% trans 'Текст' %} </label>
            {{ form.content_new_post }}
            <div class="invalid-feedback">
                {{ form.content_new_post.errors }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.category.id_for_label }}"> {% trans 'Категория' %} </label>
            {{ form.category}}
            <div class="invalid-feedback">
                {{ form.category.errors }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.author.id_for_label }}"> {% trans 'Автор' %} </label>
            {{ form.author }}
            <div class="invalid-feedback">
                {{ form.author.errors }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.is_published.id_for_label }}"> {% trans 'Опубликовано' %} </label>
            {{ form.is_published }}
            <div class="invalid-feedback">
                {{ form.is_published.errors }}
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block">{%  trans 'Опубликовать' %} </button>

    </form>

    {% endblock header %}
{#{% endcache %}#}

{% else %}
    <p>{% trans 'Извините, но лимит публикаций на сегодня исчерпан. Попробуйте завтра.' %}</p>
{% endif %}

{% endblock content %}

module_D/D14_Module_localization/templates/post_delete.html
{% extends 'flatpages/default.html' %}
{% load censor %} <!-- не забываем заранее загружать наши фильтры! -->
{% load i18n %}


{% block title %} Post_delete {% endblock title %}

{% block content %}

<br>
<h2> {%  trans 'Действительно хотите удалить публикацию?' %} </h2>
<hr>
<br>

{{ post.time_in_new_post|date:'d M Y H:i' }},
<p>{{ post.author.author }}
<p>{{ post.content_new_post|censor:'@#%&$'|truncatewords:15}}


<form method="POST">
    {% csrf_token %}
    <input type="submit" value='{% trans "Да, удалить" %}'></form>


{% endblock content %}

module_D/D14_Module_localization/templates/post_detail.html
{% extends 'flatpages/default.html' %}
{% load censor %} <!-- не забываем заранее загружать наши фильтры! -->
{% load i18n %}

{% block title %} Post detail {% endblock title %}

{% block content %}
{% comment %}Кэшируем отдельный блок на 30 секунд{% endcomment %}
{% load cache %}
    {% cache 30 header %}
        {% block header %}
        {% endblock header %}
    {% endcache %}


<br><br>
<h3> {{ post.title|censor:'@#%&$' }} </h3>
<hr>

<br><br>

<h5> {{ post.author.author }}, {{ post.time_in_new_post|date:'d M Y H:i' }}</h5>

<div>
    {% if PCC %}
    {{ post.get_new_post_display }} {% trans 'из категории' %}: <strong>{{ PCC }}</strong>
    <div>
        {% if user.is_authenticated %}
            {% if not is_subscriber %}
            <form action="{% url 'subscribe' PCC.pk %}" method="POST">
            {% csrf_token %}
            <button title= "{% trans 'Подписаться' %}" style="border-radius: 5px; box-shadow: 0px 1px 3px; font-size: 16px;">
                {% trans "Подписаться" %}</button>
            </form>
        {% endif %}
        {% if is_subscriber %}
            <form action="{% url 'subscribe' PCC.pk %}" method="POST">
            {% csrf_token %}
            <button title="{% trans 'Отписаться' %}" style="border-radius: 5px; box-shadow: 0px 1px 3px; font-size: 16px;">
                {% trans 'Отписаться' %}</button>
            </form>
        {% endif %}
    {% endif %}
    </div>

    <br><br>

    <p>{{ post.content_new_post|censor:'@#%&$' }}</p>
    <br>

    {% else %}
        <h2> {% trans 'Категория не присвоена!' %}</h2>
    {% endif %}

</div>

{% endblock content %}

module_D/D14_Module_localization/templates/post_search.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load censor %}

{% block title %}Search{% endblock title %}

{% block content %}

<h2>{% trans 'Поиск публикаций' noop%} </h2><hr>

<form method="GET">
    {{ filter.form }}
    <input type="submit" value="{% trans 'Найти' noop%}">
</form>

<table>
    <tr>
        <th>{% trans 'Дата публикации' %}</th>
        <th>{% trans 'Автор' %}</th>
        <th>{% trans 'Заголовок' %}</th>
        <th>{% trans 'Текст' %}</th>
    </tr>
   {% for post in filter.qs %}
    <tr>
        <td>{{ post.time_in_new_post|date:'d F Y H:i' }}</td>
        <td>{{ post.author.author }}</td>
        <td><a href="{% url 'post_detail' post.id %}">{{ post.title|truncatewords:10|censor:'@#%&$' }} </a> </td>
        <td>{{ post.content_new_post|truncatewords:10|censor:'@#%&$' }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

module_D/D14_Module_localization/templates/post_update.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
 
{% block title %} Update {% endblock title %}
 
{% block content %}
<h3> {% trans 'Редактирование' %} </h3>
<hr><br>

<form method="post">
    {% csrf_token %}
    {{ form}}
    <input type="submit" value=" {% trans 'Редактировать' %} ">
</form>


{% endblock content %}

module_D/D14_Module_localization/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %} <!-- тег для работы с часовыми поясами -->
{% load censor %} <!-- не забываем заранее загружать наши фильтры! -->


{% block title %} {%  trans 'Главная страница портала' %} {% endblock title %}
{% block content %}



<!--<h3>{{ time_now|date:'d M Y' }}</h3>  -->
<!--<h3> {{ value1|default_if_none:"ничего" }} </h3> -->
<!-- <h2>Всего публикаций - {{posts|length}} </h2> -->
<h3>{%  trans 'Всего публикаций' %} - {{all_posts}} </h3>
<hr>

{% if user.is_authenticated %}
<h5> {% trans 'Страница авторизованного пользователя' %} <b> {{request.user.username}} </b></h5>
{% endif %}



    <p align="left"><a href="{% url 'post_search.html' %}"> <u><b> {% trans 'Поиск' %} </b></u></a></p>
    <p align="left"> <a href="{% url 'post_create.html' %}"> <u><b> {% trans 'Добавить публикацию' %} </b></u></a></p>


{% if posts %}
    <table>
        <tr>
            <th> {% trans 'Дата публикации' %}</th>
            <th>{% trans 'Автор' %}</th>
            <th> {% trans 'Заголовок' %} </th>
            <th> {% trans 'Текст' %}</th> <!--<th>Категория</th>-->
        </tr>
        {% for post in object_list %}
             <tr>
                <td>{{ post.time_in_new_post|date:'Y-m-d H:i:s' }}</td>
                <td>{{ post.author.author }}</td>
                <td><a href="{% url 'post_detail' post.id %}">{{ post.title|censor:'@#%&$'|truncatewords:10 }}</a></td>
                <td>{{ post.content_new_post|truncatewords:10|censor:'@#%&$' }}</td>
               <!-- <td>{{ categories }}</td>-->
                <td><a href="{% url 'post_update' post.id %}"><u> {% trans 'Редактировать' %}</u></a><a>&nbsp;</a></td>
                <td><a href="{% url 'post_delete' post.id %}"><u> {% trans 'Удалить' %} </u></a></td>
             </tr>
        {% endfor %}
    </table>
<p></p>


    {% if is_paginated %}
    {% if page_obj.has_previous %}
        <a href="?page=1">{% trans "Первая" %}</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages}}">{% trans 'Последняя' %}</a>
    {% endif %}
  {% endif %}



{% else %}
    <h3>{% trans 'Новостей нет' %}</h3>

{% endif %}

{% endblock content %}